M48
; DRILL file {KiCad 9.0.0} date 2025-04-21T22:07:44+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-21T22:07:44+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X147.475Y-136.825
X156.35Y-136.75
T2
X137.5Y-45.0
X137.5Y-140.0
X182.5Y-45.0
X182.5Y-140.0
M30
